### ISSUE TITLE
Low contrast between active and non-active tabs.

### ISSUE THREAD

**Issue by whitebyte** [Lootyhoof/whitemoon#1]
Hi
This is the nicest Palemoon theme to the date. The only minor issue that it's sometimes difficult to distinguish between active and inactive tabs, especially on large number of opened tabs (see screenshot). Is there any way to do active tab some more visible?
![screenshot_20171209_012756](https://user-images.githubusercontent.com/7704186/33789296-3ed50cda-dc80-11e7-8f78-bec898f0cbce.png)

**Comment by Lootyhoof** [comment]
Thanks for pointing this out. I'll be working on an update for this theme soon, so I'll look to get this tweaked too. In the meantime, it should be possible to add this to `userChrome.css`, taking note to replace the `COLOR-HERE` with your choice:

````
.tabbrowser-tab:not([selected=true]):not(:-moz-lwtheme) {
  background-color: COLOR-HERE !important;
}
````

**Comment by whitebyte** [comment]
Thank you for the feedback!
