### ISSUE TITLE
Audio indicator isn't black anymore once the tab it's in selected (Mac).

### ISSUE THREAD

**Issue by Peacock365** [Lootyhoof/whitemoon#2]
Hi Lootyhoof,

I discovered an issue with the tab audio indicator appearance on macOS: If you select the tab that has an audio indicator symbol in it, the audio indicator appearance changes to white. A white audio indicator is hard to see on a white background.

If the tab with audio indicator isn't selected, the appearance is normal (black audio indicator on white background).

Pale Moon 28.3.0, macOS 10.14 Mojave.

Please fix, thank you.

**Comment by Lootyhoof** [comment]
Does this happen with my other themes too? If so I might need to update most of them for this...which could take a little while, unfortunately.

In the meantime though, you could try this, in [userChrome.css](http://kb.mozillazine.org/index.php?title=UserChrome.css&printable=yes) or [Stylem](https://addons.palemoon.org/addon/stylem/):

````
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");

.tabbrowser-tab,
.tab-icon-sound {
  color: #000 !important;
}
````

**Comment by Peacock365** [comment]
Success! The code you've posted has fixed the issue, Lootyhoof! 

> Does this happen with my other themes too?

I have no idea, as I only use WhiteMoon. If you want me to, I can test other themes as well, if need be.

**Comment by Lootyhoof** [comment]
Thanks for checking. It's fine, I'll get to them, since they mostly all style this in the same way.
